### ISSUE TITLE
Uncaught error at extendBasis

### ISSUE THREAD

**Issue by garytokyo** [d3/d3-hierarchy#100]
Could someone tell me what would cause this error? `Uncaught Error at extendBasis (enclose.js:46)`. Not sure if this is a bug with d3-hierarchy or just the way I am using it.

I am using a React component based on [this](https://github.com/kauffecup/react-bubble-chart) which uses d3 (I have updated it to use v4). I am also using React Router to create an SPA. My Bubble chart is on the home route all works fine apart from when navigating to another route and then back again. Once one navigates back to the home route this error occurs.

Any help appreciated.

**Comment by mbostock** [comment]
That is probably a numerical issue in computing the basis. I would love to investigate this issue further, but I won’t be able to do so without knowing the inputs to packEnclose (or whatever pack methods you are using) so that I can reproduce the error. Please post a reduced test case that exhibits the error and I will reopen and investigate. Thank you!

**Comment by dheygere** [comment]
FYI I had the same Error thrown. In my case it was because I supplied a width and height of zero to _pack().size([width, height])_.

Ultimately that was a cross-browser issue: in Firefox getting the width and height of a container with code such as _svg.node().clientWidth_ returned 0. I fixed my issue by using _svg.node().getBoundingClientRect().width_ instead.

**Comment by aarthi0808** [comment]
Facing same kind of issue in using d3-hierarchy for pack layout. Please check the data i am using,
`             ["a",5.473061352023348e+21],
              ["b", 1.1729457180068344e+21],
               ["c", 1023, 1]`

Checkout the error stack messages

> main-constructor.js:1357 Error
    at extendBasis (d3-hierarchy.v1.js:353)
    at enclose (d3-hierarchy.v1.js:321)
    at packEnclose (d3-hierarchy.v1.js:536)
    at d3-hierarchy.v1.js:626
    at Node.node_eachAfter [as eachAfter] (d3-hierarchy.v1.js:140)
    at pack (d3-hierarchy.v1.js:586)
    at getPackNodeDescendants (packedbubblechart.js:476)
    at SVGGElement.<anonymous> (packedbubblechart.js:137)
    at Selection.selection_each [as each] (d3.js:1215)
    at chart (packedbubblechart.js:46)
