### ISSUE TITLE
Wrap rather than mutate input data?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-hierarchy#13]
Related mbostock/d3#1145 mbostock/d3#1929.

Also this was my [“\#1” regret](https://www.reddit.com/r/dataisbeautiful/comments/3k3if4/hi_im_mike_bostock_creator_of_d3js_and_a_former/cuukqok) on my AMA.

**Comment by idibidiart** [comment]
@mbostock 

Could you make use [ImmutableJS] (https://facebook.github.io/immutable-js/) or another implementation of persistent data structure so that we may leverage the efficiencies of structural sharing? 

I went down the [HTML5 Structured Cloning] (https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) approach and it works well with D3 EXCEPT it is really slow to clone in general. 

Persistent Data Structures like those implemented by ImmutableJS are extremely memory efficient and immutable by design. It also allows for rendering optimization with React due to mutation creating a a new reference identity and being able to use reference equality to determine if two deep tree structures are equal without comparing the actual tree data. Given React is being used more and more in general UI development, it may make a lot of sense to use ImmutableJS.

@leeb (on twitter) is the maintainer of that library.

Cheers 

Marc

**Comment by idibidiart** [comment]
If not using ImmutableJS then maybe D3 will have its own implementation of HAMT...? I trust your choice will focus on performance... 

http://blog.mattbierner.com/hash-array-mapped-tries-in-javascript/

**Comment by mbostock** [comment]
Fixed in #14.
