### ISSUE TITLE
How to avoid treemap tile shuffling?

### ISSUE THREAD

**Issue by mmahandev** [d3/d3-hierarchy#158]
When adding transitions how can I avoid reshuffling of the tiles? For example having initial data of `[2, 2, 2, 2, 1]` and then updating to `[5, 2, 2, 2, 1]` will cause the first tile to move, even with d3.treemapResquarify.

Example reduced testcase: https://codepen.io/mmahandev/pen/MWwOoOg

**Comment by mbostock** [comment]
The problem is that you’re passing in a new instance of d3.hierarchy, so you’re throwing away the old layout and hence the information needed to preserve the old configuration. In other words, you need to call *root*.sum(…) on the same *root* instance that you previously passed to the treemap layout, with an accessor that returns the new value for each node.

Here’s an example:

https://observablehq.com/d/23ce62d72f485421

**Comment by mmahandev** [comment]
@mbostock Exactly what I needed. Thank you for such a quick reply!

**Comment by HoplaGeiss** [comment]
@mbostock do you have a similar example for a tree?
I am trying to follow your suggestion from this issue: https://github.com/d3/d3-hierarchy/issues/139
And trying to call `d3.hierarchy` every time I remove or add a node, but that reshuffles the tree.
