### ISSUE TITLE
Treemap Horizontal/Vertical Layout

### ISSUE THREAD

**Issue by ahoiin** [d3/d3-hierarchy#49]
Hi,
how can I set the horizontal or vertical layout for the treemap independent of the width/height ration?
I would like to create a wide treemap with the fields appearing underneath thus the labels are better readable. 
Screenshot 1 (wider than higher) should be like Screenshot 2 (higher than wider).
<img width="803" alt="screenshot 2016-06-29 21 40 08" src="https://cloud.githubusercontent.com/assets/1630274/16466161/5ec6c0b6-3e42-11e6-89ee-04497756ea64.png">
<img width="691" alt="screenshot 2016-06-29 21 40 56" src="https://cloud.githubusercontent.com/assets/1630274/16466162/5eca9100-3e42-11e6-8c0d-96ce9d720f4b.png">

**Comment by mbostock** [comment]
You can’t really do this using [*squarify*.ratio](https://github.com/d3/d3-hierarchy#squarify_ratio) because that *ratio* is independent of the orientation and is always greater than or equal to one.

If you are willing to give up inner padding, you can approximate this result by instead using a *squarify*.ratio of one, and then stretching the resulting treemap to fit the desired target ratio. Here’s an example:

http://bl.ocks.org/mbostock/5c50a377e76a1974248bd628befdec95

**Comment by ahoiin** [comment]
Yeah that should work. Thanks for that.
In that case w and h should be greater 0 otherwise -1px will break the layout.
`var w = Math.round(d.x1 * ratio) - Math.round(d.x0 * ratio); return (w > 0 ? w - 1 : 0) + "px";`
