### ISSUE TITLE
How to find a given node within a hierarchy/layout?

### ISSUE THREAD

**Issue by Ptival** [d3/d3-hierarchy#58]
Back in d3 3.x, d3 would populate my nodes with hierarchical/layout data (fields like `parent`, `x`, `y`).

Therefore, if I had a `rootNode`, and an `otherNode` that was reachable from `rootNode`, I could access `otherNode.parent`, `otherNode.x`, etc.

With d3 4.x, d3 creates a `hierarchyRootNode` which contains the field `parent`, and whose `data` field contains my `rootNode`. Similarly, were I to search for it from `hierarchyRootNode`, I could find another hierarchy node whose `data` field points to my `otherNode`.

My question is: is there an existing way of obtaining that node? That is, given a data node, how can I best obtain its hierarchy container?

I am currently doing an inefficient:
`const hierarchyOtherNode = hierarchyRootNode.descendants().find(d => d.data.id === otherNode.id)`

Is there a simpler way to get around this?

**Comment by mbostock** [comment]
This is an open-ended question as there are lots of ways to solve this problem. Two options immediately come to mind.

One option is that wherever your code currently has *data* nodes, change that code so that it has *hierarchy* nodes. If you always have *hierarchy* nodes, you can use *hierarchy*.parent and *hierarchy*.children to search, and you never need to map from a *data* node to a *hierarchy* node. Ideally, you do this when you load your data, so your code only sees hierarchy nodes and never the “raw” data (be it from CSV, JSON, whatever).

Another option would be to add bidirectional links from the *data* nodes to the containing *hierarchy* nodes. There’s already *hierarchy*.data to link from *hierarchy* to *data*, but you can iterate over the *hierarchy* and add a back-link:

```js
root.each(function(node) {
  node.data.node = node;
});
```

This approach assumes there is a 1-to-1 relationship between the *data* and the *hierarchy*, which is probably the case, but isn’t required. (As in, this approach precludes you from using the same data to generate multiple hierarchical visualizations that share the same data object.)

A third approach would be to create a Map that explicitly maps from *data* to *hierarchy*. That way if you want multiple *hierarchy*s you can have multiple *map*s.

If you want more assistance, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by karlitos** [comment]
I would like to avoid creating a new issue for this, so I post my question here.

I wonder if there is a possibility to create the back-links/mapping on-the-fly when calling `d3.hierarchy` , `d3.stratify()` so I don't need to traverse the tree 2.nd time
```
root.each(function(node) {
...
});
```

Background: I would like to create a id -> hierarchy node look-up table os I can access nodes instantly.
