### ISSUE TITLE
Why use undefined for leaf nodes rather than an empty list of children?

### ISSUE THREAD

**Issue by Ptival** [d3/d3-hierarchy#60]
It seems to be one of those JavaScriptisms that really infuriate me, but I will leave this as a suggestion.

The `hierarchy` method fills the `children` field with a list of children if any, and `undefined` otherwise.

It seems to me that returning an empty list would be much more elegant and practical. For instance I could do:

```
// using ES5+ operators
node.children.map(...)
node.children.reduce(...)
```

Is there any good reason for not returning an empty list?
Good thing TypeScript with `strictNullChecks` warned me...

**Comment by mbostock** [comment]
It was a matter of preference. I preferred to use null to represent leaf nodes rather than an empty array, but certainly it would have been reasonable to use an empty array instead. I am unlikely to change the behavior now as it would not be backwards-compatible, although I suppose I could consider it for a future major version.
