### ISSUE TITLE
Receive node instead of node's data on node.sum()

### ISSUE THREAD

**Issue by snolflake** [d3/d3-hierarchy#79]
I had the same issue described on #50 I believe. 
Sorry if I'm missing something here but `node.sum` only provides the [node data instead of the node itself](https://github.com/d3/d3-hierarchy/blob/master/src/hierarchy/sum.js#L3) and when the root node is generated with stratify it doesn't necessarily have a `children` property.

If someone wants to weight each node's value based on its position in the hierarchy for example, again, sending only the node data is more limiting than convenient.

Without breaking the current API, would be really great to have an out of box alternative to sum using the nodes instead of their data.

Modifying the data is an easy workaround but not ideal in some cases:
```
root.each(node => {
  node.data.value = node.children ? 0 : 1
})
root.sum(data => data.value)
```

**Comment by mbostock** [comment]
For the specific use case you describe, see the new [*node*.count](https://github.com/d3/d3-hierarchy/blob/master/README.md#node_count) introduced in [d3-hierarchy@1.1.0](https://github.com/d3/d3-hierarchy/releases/tag/v1.1.0) ([d3@4.5.0](https://github.com/d3/d3/releases/tag/v4.5.0)).

Changing *node*.sum so that the accessor is passed the *node* rather than *node*.data would require a major version change, and even then, would be quite disruptive since it’s a subtle change. So it’s unlikely that this will happen.

For other use cases, probably you best bet is to look at how *node*.sum and *node*.count are implemented, and emulate that.

https://github.com/d3/d3-hierarchy/blob/master/src/hierarchy/sum.js
https://github.com/d3/d3-hierarchy/blob/master/src/hierarchy/count.js

**Comment by snolflake** [comment]
Thanks for the clarification. I agree with you about the API change.
I tough I was getting `undefined` on `node.count` because `d3.stratify` output was different from `d3.hierarchy` somehow. But in fact I was still using d3@4.4.0.

Thanks again!
