### ISSUE TITLE
default radius accessor for pack distorts data

### ISSUE THREAD

**Issue by finnfiddle** [d3/d3-hierarchy#86]
Hi there. D3 is great!

Correct me if I'm wrong about this but I noticed the default radius accessor for the Pack Layout is `Math.sqrt`. In most pack examples Ive seen circles used to display the nodes but this default accessor would distort the data for circles. A node with value of 1 would not be half the area of a node with a value of 2. However, if we used squares to render the nodes then it would be representative right?

So I propose the default accessor be `function(d) { return Math.sqrt(d / Math.PI); }` because this would represent values with circles accurately.

Another issue with the API (maybe I should open another issue?) is that if you specify a custom radius accessor it doesnt scale all the radiuses down to fit inside the available space. You need to write your own packing algorithm right? Which defeats the purpose of using the Pack in the first place. Maybe I don't understand it properly - please correct me if I am wrong.

If I'm right though maybe a good idea is to separate the scaling down option so that it isnt connected to the radius accessor. You can set a custom radius accessor AS WELL as choose whether all radiuses should be scaled down or not.

 Thanks in advance for your feedback

**Comment by mbostock** [comment]
The default radius accessor defaults to null, but it is true that when the radius accessor is null, the radius of the circles is proportional to the square root of the node value. This default accessor is implemented as:

```js
function defaultRadius(d) {
  return Math.sqrt(d.value);
}
```

If the radius is proportional to the square root of the value, then the area is proportional to the value, which is the intention. That is because *area* = π × *radius*². To use your example:

> A node with value of 1 would not be half the area of a node with a value of 2.

Ignoring scaling, the radius of a node with value 1 would be sqrt(1) = 1; the radius of a node with value 2 would be sqrt(2) ≅ 1.414. The respective areas would then be π * sqrt(1) * sqrt(1) and π * sqrt(2) * sqrt(2). Again ignoring the constant scaling of π (which does not affective the relative proportions of the circles, and again also doesn’t matter because the pack layout will rescale all the circles by a constant factor to fit the desired [layout size](https://github.com/d3/d3-hierarchy/blob/master/README.md#pack_size)), the respective areas are 1 and 2.

Your change applies a constant factor of 1 / sqrt(π) to the default radius, but a constant factor has no effect on proportionality and again would be ignored due to the rescaling that is applied to fit the overall layout size.

If you specify your own radius accessor, that radius is used exactly in the resulting output, so in that case [*pack*.size](https://github.com/d3/d3-hierarchy/blob/master/README.md#pack_size) is mostly ignored; it only determines the center point around which the circles are packed. But the circles are still packed around this point. It just means there is no automatic constant rescaling of the circles to fit within the layout size—it’s not possible to both have a fixed radius and to resize the packed circles to fit. But regardless of whether you compute the radius yourself or let the pack layout compute a radius so that the area is proportional to associated value, the pack layout will still position the circles tightly around the center of the layout.

If you have further questions, or want to discuss D3’s behavior with other users, consider using [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js), the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by finnfiddle** [comment]
Thanks for clearing that up. And I don't mean to bug  - I know you closed this already - but see this image of what I am trying to accomplish:
![number_picture_dot_com_v0_50](https://cloud.githubusercontent.com/assets/4628721/26219551/1a4d3e72-3c18-11e7-81c0-9519e91c6c7b.png)
It's a 2D sphere pack - so I need to specify a custom radius accessor (cube root I guess) but it's quite inconvenient that it can't be relative like the default accessor and makes the radii absolute.
Anyway I can work around it using `.sum()` - just wanted to bring it to your attention.
Thanks

**Comment by mbostock** [comment]
Right, three options:

1. Use [*node*.sum](https://github.com/d3/d3-hierarchy/blob/master/README.md#node_sum) with an accessor that returns a number proportional to the desired circle’s planar area, not spherical area.

2. Use [*pack*.radius](https://github.com/d3/d3-hierarchy/blob/master/README.md#pack_radius) and either compute the appropriate radius yourself based on the desired layout area, or rescale the entire layout after letting the pack layout do its thing.

3. Don’t use spheres. 😜 People are (slightly) better at comparing the relative planar areas of circles to the relative volume of spheres. See [Cleveland & McGill](http://info.slis.indiana.edu/~katy/S637-S11/cleveland84.pdf).

**Comment by finnfiddle** [comment]
yeah ok Ill go with option 1.
Im actually trying to illustrate number 3 ;)
