### ISSUE TITLE
Recursive data to hierarchy() causes stall.

### ISSUE THREAD

**Issue by untaugh** [d3/d3-hierarchy#87]
Recursive data, as in:
```
var d1 = {'children' : []};
d1['children'].push(d1);
var d = {'children' : [d1]}; 
var root = d3.hierarchy(d);
```

Causes browser to stall. It's invalid data, but maybe it should be detected and handled.

**Comment by mbostock** [comment]
I don’t think this is possible in general, since the *children* accessor can be specified dynamically, so you can’t assume that the output hierarchy is cyclical just because the input data structure is cyclical. For example:

```js
var i = 0,
    data = {},
    root = d3.hierarchy(data, () => ++i < 5 ? new Array(2).fill(data) : []);
```

That said, you could enforce this test for the default children accessor. At any rate, I don’t currenty feel it’s worth it to enforce this test.
